version: '3.8'

services:
  db:
    image: postgres
    container_name: salles_api_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sallesapi
    ports:
      - 5432:5432
    volumes:
      - ./local/db:/var/lib/postgresql/data
    networks:
      - salles_api_network

  redis:
    image: redis
    container_name: salles_api_redis
    ports:
      - 6379:6379
    volumes:
      - ./local/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-insight:
    image: redislabs/redisinsight:latest
    ports:
      - 8001:8001
    environment:
      - REDIS_CONNECTION_HOSTS=redis:6379

networks:
  salles_api_network:
    driver: bridge
