version: '3.8'

services:
  db:
    image: postgres
    container_name: salles_api_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sallesapi
    ports:
      - "5432:5432"
    volumes:
      - ./local/db:/var/lib/postgresql/data
    networks:
      - salles_api_network

networks:
  salles_api_network:
    driver: bridge
